version: 1
builder:
  configs:
  - platform: ios
    scheme: ComposableArchitecture
  - platform: macos-xcodebuild
    scheme: ComposableArchitecture
  - platform: tvos
    scheme: ComposableArchitecture
  - platform: watchos
    scheme: ComposableArchitecture
  - documentation_targets: [ComposableArchitecture]
    swift_version: 5.9
